### ISSUE TITLE
Convert silicoid portraits to lithoids?

### ISSUE THREAD

**Issue by zokradonh** [mindgamer-net/steam-stellaris-r27-portraits#4]
What do you think?

In fact silicoids and lithoids are two different things, but lithoids is the better name in my opinion since all of the biological species could either be carbon or silicon based lifeforms.

Actual effect: Those that use silicoids right now are unable to use them anymore if they don't have this DLC. But those that have can use them as lithoids which gives them the gameplay effects (+50% habability etc.).

Workaround:
Make two categories: R27 Silicoids (same like old) and R27 Lithoids (DLC dependent with the Lithoid trait)

Although I don't like spamming the appearence category list...
Maybe one could combine BioMachine and Silicoid to same BioFake Class.

**Comment by mindgamer-net** [comment]
Generally I like the idea. However I'd hate to lose the Silicoid section for people who do not have the Lithoids expansion.

I think it is also possible to add a negative expansion check? Make the section true Lithoids if the user has an expansion and leave them the current R27 Silicoids if there is no such expansion? Otherwise the only way to find the Silicoid portraits would be under the BioFake section. I think it would be better to have only duplicates there, no original portraits.

There seems to be this flag atm: `playable = { has_lithoids = yes }`. I'd expect the 'no' value to work as described. What do you think?

I have another question for you. I have held off upgrading the mod to 2.5.* so far because the Discord mod channel seems to recommend holding off on this. What do you think?

**Comment by mindgamer-net** [comment]
Nevermind that last question. I found out how to update the mod so that it retains compatibility with 2.3 branch

**Comment by zokradonh** [comment]
> There seems to be this flag atm: `playable = { has_lithoids = yes }`. I'd expect the 'no' value to work as described. What do you think?

Yeah, sounds like a good idea.

So we don't need to add them to the BioFake category except we want to give the lithoids DLC owners the possibility to play them without lithoid trait.
It is even possible to add them to BioFake only if it is a lithoids DLC owner.

**Comment by zokradonh** [comment]
I have implemented this in a398b8b784089d150324e3baef74b56a136d2c61
Though it depends on the octeelan pull request #5 that need to be merged first.

**Comment by mindgamer-net** [comment]
I merged #5. Maybe make a PR for this additional change as well? I will try to test them and push to Steam in a couple of days. Been AFK due to illness lately, hopefully will feel up to some code poking soon.

**Comment by zokradonh** [comment]
Oh, get well soon!
Now I had the time to make the other pull request. Thank you.
